version: '3.8'

services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile.dev
    ports:
      - "9527:9527"
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - ENVIRONMENT=development
      - PORT=9527
      - CORS_ORIGINS=https://shigekikozawa.github.io,https://nagara-giki.app,https://gdrive-audio-playerapi-production.up.railway.app
    volumes:
      - ./apps/api:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 9527

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:9527
      - NEXT_PUBLIC_FRONTEND_URL=http://localhost:3000
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    depends_on:
      - api 